// corpus.js — Base de questions NLP
module.exports = {
  retrait: [
    'comment retirer de l argent dans mon compte en utilisant ma carte',
    'comment faire un retrait avec ma carte bancaire',
    'je veux retirer de l argent au guichet automatique',
    'comment utiliser le distributeur automatique de billets',
    'comment sortir de l argent de mon compte',
    'je n arrive pas a retirer de l argent au DAB',
    'le distributeur refuse ma carte comment faire',
    'combien je peux retirer par jour avec ma carte',
    'quelle est ma limite de retrait journaliere',
    'retrait', 'retirer argent', 'DAB', 'distributeur', 'guichet automatique',
    'retirer cash', 'limite retrait', 'plafond retrait', 'sortir argent', 'retrait carte',
  ],
  creation_compte: [
    'comment ouvrir un compte bancaire dans votre banque',
    'quels sont les documents necessaires pour ouvrir un compte',
    'je veux creer un nouveau compte chez vous',
    'comment devenir client de votre banque',
    'quelle est la procedure pour ouvrir un compte',
    'combien coute l ouverture d un compte',
    'est ce qu on peut ouvrir un compte en ligne',
    'quels sont les types de comptes disponibles',
    'je veux un compte epargne comment faire',
    'quel est le depot minimum pour ouvrir un compte',
    'ouvrir compte', 'nouveau compte', 'creer compte', 'inscription',
    'devenir client', 'compte epargne', 'compte courant', 'compte professionnel',
  ],
  horaires: [
    'a quelle heure ouvre la banque le matin',
    'est ce que la banque est ouverte le samedi',
    'quels sont vos horaires d ouverture cette semaine',
    'jusqu a quelle heure vous etes ouverts',
    'vous fermez a quelle heure le vendredi',
    'est ce que vous travaillez le dimanche',
    'la banque est elle ouverte aujourd hui',
    'horaires', 'heures ouverture', 'ouvert samedi', 'ferme dimanche', 'heure fermeture',
  ],
  cartes: [
    'j ai perdu ma carte bancaire que dois je faire',
    'ma carte a ete volee comment la bloquer',
    'comment faire opposition sur ma carte',
    'comment renouveler ma carte bancaire expiree',
    'ma carte est avalee par le distributeur',
    'comment debloquer ma carte bancaire',
    'comment demander une nouvelle carte',
    'comment changer mon code pin',
    'j ai oublie mon code pin que faire',
    'comment augmenter la limite de ma carte',
    'ma carte ne fonctionne pas chez les commercants',
    'carte perdue', 'carte volee', 'bloquer carte', 'opposition carte',
    'renouveler carte', 'code pin oublie', 'carte expiree', 'carte bloquee',
  ],
  virement: [
    'comment faire un virement vers un autre compte',
    'comment envoyer de l argent a quelqu un',
    'comment transferer de l argent vers une autre banque',
    'quel est le delai pour un virement national',
    'combien coute un virement international',
    'comment envoyer de l argent a l etranger',
    'comment annuler un virement en cours',
    'virement', 'transfert argent', 'envoyer argent', 'virement international',
    'delai virement', 'frais virement', 'mobile money',
  ],
  localisation: [
    'ou se trouve l agence la plus proche de chez moi',
    'quelle est l adresse de votre siege social',
    'vous avez une agence a bobo dioulasso',
    'est ce qu il y a une agence a koudougou',
    'comment venir a votre agence principale',
    'adresse agence', 'localisation', 'agence proche', 'ou etes vous', 'agences disponibles',
  ],
  reclamation: [
    'reclamation',
    'faire une reclamation',
    'je veux faire une reclamation',
    'soumettre une reclamation',
    'deposer une reclamation',
    'faire une plainte',
    'je veux faire une plainte',
    'porter plainte',
    'signaler un probleme',
    'je veux me plaindre',
    'j ai un probleme avec mon compte',
    'erreur sur mon compte',
    'un virement a ete debite de mon compte mais n est pas arrive',
    'j ai ete debite deux fois pour la meme operation',
    'de l argent a disparu de mon compte sans raison',
    'on m a preleve des frais que je ne comprends pas',
    'je veux porter plainte contre votre banque',
    'je suis tres mecontent du service que j ai recu',
    'je veux signaler un probleme avec mon compte',
    'plainte', 'probleme compte', 'erreur virement',
    'debite par erreur', 'contester', 'transaction inconnue',
  ],
  solde: [
    'comment consulter mon solde bancaire',
    'comment voir mon solde sur l application',
    'comment obtenir mon releve de compte',
    'je veux voir mes dernieres transactions',
    'comment verifier mes mouvements de compte',
    'solde compte', 'voir solde', 'releve compte', 'historique transactions',
    'mouvements compte', 'extrait compte', 'combien j ai',
  ],
  appli: [
    'comment telecharger votre application mobile',
    'comment activer l application bancaire',
    'j ai des problemes pour me connecter a l application',
    'comment reinitialiser mon mot de passe de l application',
    'l application ne fonctionne pas sur mon telephone',
    'application mobile', 'appli banque', 'connexion application',
    'mot de passe appli', 'telecharger appli', 'service en ligne',
  ],
  salutation: [
    'bonjour', 'bonsoir', 'salut', 'allo', 'hello', 'salam',
    'bonjour j ai besoin d aide', 'je voudrais des informations',
    'pouvez vous m aider', 'j ai une question',
    'aide', 'help', 'menu', 'demarrer', 'commencer', '1', 'start',
  ],
};
