// corpus.js — Base de questions NLP
module.exports = {
  retrait: [
    'comment retirer de l argent dans mon compte en utilisant ma carte',
    'comment faire un retrait avec ma carte bancaire',
    'je veux retirer de l argent au guichet automatique',
    'comment utiliser le distributeur automatique de billets',
    'comment sortir de l argent de mon compte',
    'je n arrive pas à retirer de l argent au DAB',
    'le distributeur refuse ma carte comment faire',
    'combien je peux retirer par jour avec ma carte',
    'quelle est ma limite de retrait journalière',
    'retrait', 'retirer argent', 'DAB', 'distributeur', 'guichet automatique',
    'retirer cash', 'limite retrait', 'plafond retrait', 'sortir argent', 'retrait carte',
  ],
  creation_compte: [
    'comment ouvrir un compte bancaire dans votre banque',
    'quels sont les documents nécessaires pour ouvrir un compte',
    'je veux créer un nouveau compte chez vous',
    'comment devenir client de votre banque',
    'quelle est la procédure pour ouvrir un compte',
    'combien coûte l ouverture d un compte',
    'est ce qu on peut ouvrir un compte en ligne',
    'quels sont les types de comptes disponibles',
    'je veux un compte épargne comment faire',
    'quel est le dépôt minimum pour ouvrir un compte',
    'ouvrir compte', 'nouveau compte', 'créer compte', 'inscription',
    'devenir client', 'compte épargne', 'compte courant', 'compte professionnel',
  ],
  horaires: [
    'à quelle heure ouvre la banque le matin',
    'est ce que la banque est ouverte le samedi',
    'quels sont vos horaires d ouverture cette semaine',
    'jusqu à quelle heure vous êtes ouverts',
    'vous fermez à quelle heure le vendredi',
    'est ce que vous travaillez le dimanche',
    'la banque est elle ouverte aujourd hui',
    'horaires', 'heures ouverture', 'ouvert samedi', 'fermé dimanche', 'heure fermeture',
  ],
  cartes: [
    'j ai perdu ma carte bancaire que dois je faire',
    'ma carte a été volée comment la bloquer',
    'comment faire opposition sur ma carte',
    'comment renouveler ma carte bancaire expirée',
    'ma carte est avalée par le distributeur',
    'comment débloquer ma carte bancaire',
    'comment demander une nouvelle carte',
    'comment changer mon code pin',
    'j ai oublié mon code pin que faire',
    'comment augmenter la limite de ma carte',
    'ma carte ne fonctionne pas chez les commerçants',
    'carte perdue', 'carte volée', 'bloquer carte', 'opposition carte',
    'renouveler carte', 'code pin oublié', 'carte expirée', 'carte bloquée',
  ],
  virement: [
    'comment faire un virement vers un autre compte',
    'comment envoyer de l argent à quelqu un',
    'comment transférer de l argent vers une autre banque',
    'quel est le délai pour un virement national',
    'combien coûte un virement international',
    'comment envoyer de l argent à l étranger',
    'comment annuler un virement en cours',
    'virement', 'transfert argent', 'envoyer argent', 'virement international',
    'délai virement', 'frais virement', 'mobile money',
  ],
  localisation: [
    'où se trouve l agence la plus proche de chez moi',
    'quelle est l adresse de votre siège social',
    'vous avez une agence à bobo dioulasso',
    'est ce qu il y a une agence à koudougou',
    'comment venir à votre agence principale',
    'adresse agence', 'localisation', 'agence proche', 'où êtes vous', 'agences disponibles',
  ],
  reclamation: [
    'un virement a été débité de mon compte mais n est pas arrivé',
    'j ai été débité deux fois pour la même opération',
    'de l argent a disparu de mon compte sans raison',
    'on m a prélevé des frais que je ne comprends pas',
    'je veux porter plainte contre votre banque',
    'je suis très mécontent du service que j ai reçu',
    'je veux signaler un problème avec mon compte',
    'réclamation', 'plainte', 'problème compte', 'erreur virement',
    'débité par erreur', 'contester', 'signaler problème', 'transaction inconnue',
  ],
  solde: [
    'comment consulter mon solde bancaire',
    'comment voir mon solde sur l application',
    'comment obtenir mon relevé de compte',
    'je veux voir mes dernières transactions',
    'comment vérifier mes mouvements de compte',
    'solde compte', 'voir solde', 'relevé compte', 'historique transactions',
    'mouvements compte', 'extrait compte', 'combien j ai',
  ],
  appli: [
    'comment télécharger votre application mobile',
    'comment activer l application bancaire',
    'j ai des problèmes pour me connecter à l application',
    'comment réinitialiser mon mot de passe de l application',
    'l application ne fonctionne pas sur mon téléphone',
    'application mobile', 'appli banque', 'connexion application',
    'mot de passe appli', 'télécharger appli', 'service en ligne',
  ],
  salutation: [
    'bonjour', 'bonsoir', 'salut', 'allo', 'hello', 'salam',
    'bonjour j ai besoin d aide', 'je voudrais des informations',
    'pouvez vous m aider', 'j ai une question',
    'aide', 'help', 'menu', 'démarrer', 'commencer', '1', 'start',
  ],
};
